from pathlib import Path

GOLF_TITLE = '盛心実践会 千葉・心を高める経営を伸ばす会 佐倉　合同ゴルフコンペ'

schedule = Path('schedule.html')
s = schedule.read_text(encoding='utf-8')

if '.golf-details{' not in s:
    s = s.replace('.info{background:var(--soft);border-radius:20px;padding:22px;color:var(--muted)}', '.golf-quick{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:16px 0}.golf-quick div{background:var(--soft);border-radius:14px;padding:12px 14px}.golf-quick span{display:block;font-size:12px;color:var(--muted);font-weight:800}.golf-quick strong{display:block;color:var(--wine);margin-top:2px}.golf-details{margin-top:16px;border:1px solid var(--line);border-radius:16px;overflow:hidden;background:#fff}.golf-details summary{cursor:pointer;padding:15px 17px;font-weight:900;color:var(--wine);list-style:none}.golf-details summary::-webkit-details-marker{display:none}.golf-details summary:after{content:"＋";float:right}.golf-details[open] summary:after{content:"−"}.golf-detail-body{padding:4px 17px 19px;border-top:1px solid var(--line);font-size:14px}.golf-detail-body h3{margin:18px 0 7px;color:var(--wine);font-size:16px}.golf-detail-body p{margin:6px 0;color:var(--ink)}.golf-detail-body ul{margin:6px 0;padding-left:20px}.golf-detail-body li{margin:4px 0}.golf-times{display:grid;grid-template-columns:auto 1fr;gap:5px 14px;margin:8px 0}.golf-contact{background:var(--soft);border-radius:14px;padding:14px 16px;margin-top:12px}.golf-contact a{color:var(--wine);font-weight:800}@media(max-width:600px){.golf-quick{grid-template-columns:1fr}}.info{background:var(--soft);border-radius:20px;padding:22px;color:var(--muted)}')

old = '<article class="event"><div class="event-head"><div class="date">2026年11月24日（火）</div><h2>盛心実践会 千葉・心を高める経営を伸ばす会 佐倉　合同ゴルフコンペ</h2></div><div class="body"><div class="theme">季美の森ゴルフ倶楽部</div><p>スタート時間・参加費・組数・参加申込などの詳細は、決まり次第ご案内します。</p></div></article>'
new = '''<article class="event"><div class="event-head"><div class="date">2026年11月24日（火）</div><h2>盛心実践会 千葉・心を高める経営を伸ばす会 佐倉　合同ゴルフコンペ</h2></div><div class="body"><div class="theme">季美の森ゴルフ倶楽部</div><p>秋深まる心地よい季節に、初心者からベテランまで一緒に楽しめる合同ゴルフコンペを開催します。5組20名様、先着順です。</p><div class="golf-quick"><div><span>募集定員</span><strong>5組・20名（先着順）</strong></div><div><span>プレー費＋参加費</span><strong>14,800円＋5,000円</strong></div><div><span>申込締切</span><strong>11月16日（月）</strong></div></div><details class="golf-details"><summary>開催概要・当日の詳細を見る</summary><div class="golf-detail-body"><h3>開催場所</h3><p><strong>季美の森ゴルフ倶楽部</strong><br>〒299-3241 千葉県大網白里市季美の森南2-49<br>TEL：0475-73-0109</p><p>アクセス：千葉東金道路「山田I.C.」より約2km ／ 圏央道「東金I.C.」より約4km</p><h3>受付・スタート時間（OUTコース）</h3><div class="golf-times"><strong>08:00〜</strong><span>受付開始（クラブハウスフロント前）</span><strong>08:50</strong><span>集合・開会式（マスター室前）</span><strong>09:22</strong><span>1組目</span><strong>09:30</strong><span>2組目</span><strong>09:37</strong><span>3組目</span><strong>09:45</strong><span>4組目</span><strong>09:52</strong><span>5組目</span></div><p>※スタート時間の15分前にはティーグラウンドへお集まりください。</p><h3>費用</h3><p><strong>プレー費：14,800円</strong><br>各自フロントにてご精算ください。</p><p><strong>参加費：5,000円</strong><br>景品代。朝の受付時に集金します。</p><p><strong>懇親会参加費：7,000円</strong><br>朝の受付時に集金します。</p><h3>競技方法・賞品</h3><p>18ホールストロークプレー（新ペリア方式）</p><ul><li>順位賞（優勝・準優勝・3位）</li><li>ベスグロ賞</li><li>ブービーメーカー賞</li><li>ブービー賞</li><li>ニアピン賞（開催当日お知らせ）</li><li>参加賞</li></ul><h3>当日のタイムスケジュール（目安）</h3><div class="golf-times"><strong>08:00</strong><span>各自チェックイン・受付開始</span><strong>08:50</strong><span>開会式・ルール説明・集合写真撮影</span><strong>09:22</strong><span>第1組スタート</span><strong>15:30</strong><span>ホールアウト・入浴</span><strong>16:00</strong><span>懇親会場へ各自移動</span><strong>17:30</strong><span>表彰式＆懇親パーティー</span><strong>20:30</strong><span>解散予定</span></div><h3>懇親会場</h3><p><strong>永興（中華料理）</strong><br>千葉県千葉市中央区中央3丁目15-3 朝日プラザ千葉中央</p><h3>お申し込み</h3><div class="golf-contact"><p><strong>申込締切：11月16日（月）</strong></p><p>幹事担当：瀧 正之<br><a href="tel:09063335081">090-6333-5081</a></p><p>赤門事務局<br><a href="mailto:info@akamon.co.jp">info@akamon.co.jp</a></p><p>お申し込みの際は「氏名・連絡先・平均スコア・備考／要望」をお知らせください。</p><p>※組合せは、申込締め切り後に改めてご連絡します。</p></div></div></details></div></article>'''
if old in s:
    s = s.replace(old, new, 1)
s = s.replace('<h3>懇親会場</h3><p>', '<h3>懇親会場</h3><p><strong>懇親会のみの参加も大歓迎です！</strong></p><p>', 1)
schedule.write_text(s, encoding='utf-8')

member = Path('member.html')
m = member.read_text(encoding='utf-8')
if '.member-event{' not in m:
    m = m.replace('footer{padding:40px 0 55px', '.member-event{background:#fff;border:1px solid var(--line);border-radius:24px;padding:24px;box-shadow:0 10px 28px rgba(107,31,43,.06)}.member-event .event-label{display:inline-block;padding:4px 10px;border-radius:999px;background:var(--soft);color:var(--deep);font-size:12px;font-weight:900}.member-event h3{margin:10px 0 5px;font-size:23px;color:var(--deep)}.member-event>p{color:var(--muted);margin:5px 0}.member-event-quick{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:16px 0}.member-event-quick div{background:var(--soft);border-radius:14px;padding:12px 14px}.member-event-quick span{display:block;font-size:12px;color:var(--muted);font-weight:800}.member-event-quick strong{display:block;color:var(--deep);margin-top:2px}.member-golf-details{margin-top:12px;border:1px solid var(--line);border-radius:16px;overflow:hidden}.member-golf-details summary{cursor:pointer;padding:15px 17px;font-weight:900;color:var(--deep);list-style:none}.member-golf-details summary::-webkit-details-marker{display:none}.member-golf-details summary:after{content:"＋";float:right}.member-golf-details[open] summary:after{content:"−"}.member-golf-body{padding:4px 17px 19px;border-top:1px solid var(--line);font-size:14px}.member-golf-body h4{margin:18px 0 7px;color:var(--deep);font-size:16px}.member-golf-body p{margin:6px 0}.member-golf-body ul{margin:6px 0;padding-left:20px}.member-golf-body li{margin:4px 0}.member-golf-times{display:grid;grid-template-columns:auto 1fr;gap:5px 14px}.member-golf-contact{background:var(--soft);border-radius:14px;padding:14px 16px;margin-top:12px}.member-golf-contact a{color:var(--deep);font-weight:800}@media(max-width:760px){.member-event-quick{grid-template-columns:1fr}}footer{padding:40px 0 55px')

marker = '<section><div class="wrap"><div class="section-title"><h2>塾生限定コンテンツ</h2>'
member_section = '''<section><div class="wrap"><div class="section-title"><h2>今後のイベント</h2><p>塾生向けの開催情報</p></div><article class="member-event"><span class="event-label">11月24日（火）</span><h3>盛心実践会 千葉・心を高める経営を伸ばす会 佐倉　合同ゴルフコンペ</h3><p><strong>季美の森ゴルフ倶楽部</strong></p><p>初心者からベテランまで一緒に楽しめる秋の合同ゴルフコンペです。5組20名様、先着順で募集します。</p><div class="member-event-quick"><div><span>募集定員</span><strong>5組・20名</strong></div><div><span>プレー費＋参加費</span><strong>14,800円＋5,000円</strong></div><div><span>申込締切</span><strong>11月16日（月）</strong></div></div><details class="member-golf-details"><summary>ゴルフコンペの詳細を見る</summary><div class="member-golf-body"><h4>会場</h4><p><strong>季美の森ゴルフ倶楽部</strong><br>〒299-3241 千葉県大網白里市季美の森南2-49<br>TEL：0475-73-0109</p><p>千葉東金道路「山田I.C.」より約2km ／ 圏央道「東金I.C.」より約4km</p><h4>受付・スタート</h4><div class="member-golf-times"><strong>08:00〜</strong><span>受付開始（クラブハウスフロント前）</span><strong>08:50</strong><span>集合・開会式（マスター室前）</span><strong>09:22</strong><span>1組目</span><strong>09:30</strong><span>2組目</span><strong>09:37</strong><span>3組目</span><strong>09:45</strong><span>4組目</span><strong>09:52</strong><span>5組目</span></div><p>※スタート時間の15分前にはティーグラウンドへお集まりください。</p><h4>費用</h4><p><strong>プレー費 14,800円</strong>（各自フロント精算）<br><strong>参加費 5,000円</strong>（景品代／朝の受付時に集金）<br><strong>懇親会参加費 7,000円</strong>（朝の受付時に集金）</p><h4>競技方法・賞品</h4><p>18ホールストロークプレー（新ペリア方式）</p><ul><li>順位賞（優勝・準優勝・3位）</li><li>ベスグロ賞</li><li>ブービーメーカー賞・ブービー賞</li><li>ニアピン賞（当日発表）</li><li>参加賞</li></ul><h4>当日の予定</h4><div class="member-golf-times"><strong>08:00</strong><span>各自チェックイン・受付開始</span><strong>08:50</strong><span>開会式・ルール説明・集合写真</span><strong>09:22</strong><span>第1組スタート</span><strong>15:30</strong><span>ホールアウト・入浴</span><strong>16:00</strong><span>懇親会場へ各自移動</span><strong>17:30</strong><span>表彰式＆懇親パーティー</span><strong>20:30</strong><span>解散予定</span></div><h4>懇親会</h4><p><strong>永興（中華料理）</strong><br>千葉県千葉市中央区中央3丁目15-3 朝日プラザ千葉中央</p><h4>お申し込み</h4><div class="member-golf-contact"><p><strong>11月16日（月）まで</strong></p><p>幹事担当：瀧 正之<br><a href="tel:09063335081">090-6333-5081</a></p><p>赤門事務局<br><a href="mailto:info@akamon.co.jp">info@akamon.co.jp</a></p><p>氏名・連絡先・平均スコア・備考／要望をお知らせください。</p><p>※組合せは申込締め切り後に改めてご連絡します。</p></div></div></details></article></div></section>'''
if marker in m and 'ゴルフコンペの詳細を見る' not in m:
    m = m.replace(marker, member_section + marker, 1)
m = m.replace('<h4>懇親会</h4><p>', '<h4>懇親会</h4><p><strong>懇親会のみの参加も大歓迎です！</strong></p><p>', 1)
member.write_text(m, encoding='utf-8')
