from pathlib import Path
p=Path('member.html')
s=p.read_text(encoding='utf-8')
# Compact password guide
s=s.replace('.password-guide{margin-top:24px;background:#fff;border:1px solid var(--line);border-left:5px solid var(--deep);border-radius:16px;padding:18px 20px}.password-guide strong{display:block;color:var(--deep);font-size:17px}.password-guide p{margin:4px 0 12px;color:var(--muted);font-size:14px}.password-guide a{display:inline-flex;align-items:center;min-height:44px;padding:8px 16px;border-radius:999px;background:var(--deep);color:#fff;font-weight:800;font-size:14px}', '.password-guide{margin-top:16px;background:#fff;border:1px solid var(--line);border-left:4px solid var(--deep);border-radius:14px;padding:11px 14px;display:flex;align-items:center;gap:12px;flex-wrap:wrap}.password-guide strong{color:var(--deep);font-size:14px}.password-guide p{margin:0;color:var(--muted);font-size:13px;flex:1}.password-guide a{color:var(--deep);font-weight:900;font-size:13px;white-space:nowrap}')
# Add meeting message styles
s=s.replace('footer{padding:40px 0 55px', '.meeting-message{margin-top:18px;background:#fff;border-radius:20px;color:var(--ink);overflow:hidden}.meeting-message summary{cursor:pointer;padding:17px 20px;font-weight:900;color:var(--deep);list-style:none}.meeting-message summary::-webkit-details-marker{display:none}.meeting-message summary:after{content:"＋";float:right}.meeting-message[open] summary:after{content:"−"}.meeting-message-body{padding:0 20px 22px;border-top:1px solid var(--line);font-size:15px;line-height:1.9}.meeting-message-body p{color:var(--ink);margin:16px 0}.meeting-message-body .questions{background:var(--soft);border-radius:14px;padding:14px 16px}.meeting-message-body .questions p{margin:7px 0;font-weight:700}.meeting-message-body .signature{text-align:right;font-weight:800;color:var(--deep)}footer{padding:40px 0 55px')
# Replace password guide with compact copy
s=s.replace('<div class="password-guide"><strong>初めてログインした方へ</strong><p>仮パスワードでログインした方は、ご自身のパスワードに変更してください。</p><a href="./members/change-password.html">パスワードを変更する →</a></div>', '<div class="password-guide"><strong>初めてログインした方へ</strong><p>仮パスワードの方は、ご自身のパスワードに変更してください。</p><a href="./members/change-password.html">変更する →</a></div>')
# Insert collapsible representative message after next meeting card
needle='<a class="btn" style="background:#fff;color:#6b1f2b" href="entry.html#september">参加申込・出欠登録</a></div></div></div>'
message='''<a class="btn" style="background:#fff;color:#6b1f2b" href="entry.html#september">参加申込・出欠登録</a></div></div><details class="meeting-message"><summary>張本代表の今回の勉強会への思いを読む</summary><div class="meeting-message-body"><p><strong>「誰にも負けない努力をする」を、もう一度みんなで深く掘り下げてみませんか？</strong></p><p>盛心実践会千葉・心を高める経営を伸ばす会佐倉の会員・塾生の皆様</p><p>いつも温かいご支援とご参加をいただき、本当にありがとうございます。盛心実践会千葉 代表世話人の張本です。</p><p>あっという間に9月も後半を迎え、季節の変わり目となりました。9月29日（火）に開催いたします今月の勉強会について、私の素直な思いと共に、再度ご案内させてください。</p><p>9月のテーマは、経営12カ条の第4条「誰にも負けない努力をする」です。</p><p>誰もが知っているあまりに有名な言葉ですが、シンプルすぎるがゆえに、つい「知っているつもり」でスルーしてしまいがちな言葉だと思います。</p><p>実は、私自身がまさにそうでした。去年の勉強会を運営していたとき、私はこの、第4条の誰にも負けない努力をするを、「深める」という意識が圧倒的に足りず、1日で4条と5条を一気に詰め込み、12カ条の該当講話をみんなでただ視聴して終わらせてしまうような進行をしてしまいました。深く掘り下げずに軽く流してしまった自分を、今とても恥ずかしく、申し訳なく思っています。</p><p>その反省のきっかけとなったのが、7月と8月に参加させていただいた東京塾の12カ条勉強会でした。</p><p>運営側がどれだけ事前に深く勉強し、準備を詰め切っているかを目の当たりにし、「自分たちの学びの浅さ、準備の甘さ」に大きな反省と気づきをいただきました。</p><p>そこでもう一度、原点に戻って、誰にも負けない努力に触れている塾長の講話を沢山視聴してみました。</p><p>すると、12カ条を体系的に解説する講話の中では短く触れられているだけに見えても、塾長は様々な講話の中で、ご自身の壮絶な体験談やたとえ話を通して、この「誰にも負けない努力」について多面的・多次元に語り尽くされていることに気づきました。その総量と熱量は凄まじいものでした。</p><p>準備を進める中で、私自身の中に純粋な疑問がたくさん湧き出てきました。</p><div class="questions"><p>なぜ塾長は、あれほどの努力をずっと続けられたのだろうか？</p><p>途中で息切れせず、努力を継続するための工夫とは何だったのか？</p><p>なぜそこまでの努力が必要で、経営や人生にどんな効果をもたらすのか？</p><p>経営者一人の努力にとどまらず、どうすれば従業員みんなが自然と努力できる組織にしていけるのか？</p></div><p>盛心実践会の勉強会は、誰かが答えを教えるような勉強会ではなく、稲盛塾長の教えを全員で掘り下げて「自分たちの現場ではどうだろうか？」と、皆様と一緒に様々な角度からじっくり掘り下げ、実践できるような学びにして持ち帰る場だと思います。</p><p>また、今回はフィロソフィの学びもあえて「ベクトルを合わせる」の1項目だけに絞り、講話の視聴とディスカッションを行います。経営者の努力を独りよがりに終わらせず、社員と想いをひとつにして同じ方向へ進むにはどうすればいいのか――。第4条の努力と、ベクトルを合わせることのつながりについても、後半で皆様と本音で意見を交わし合えたらと思っています。</p><p>お互いのリアルな実践や葛藤を共有しながら、翌日からの経営の力になるような深い時間を一緒に創りましょう。皆様のご参加を心よりお待ちしております！</p><p class="signature">盛心実践会千葉 代表世話人　張本</p></div></details></div>'''
if needle in s and '張本代表の今回の勉強会への思いを読む' not in s:
    s=s.replace(needle,message,1)
p.write_text(s,encoding='utf-8')
