from pathlib import Path
import re

# The October event is generated by archive_september_patch.py.
# Apply this last so the schedule, homepage and member portal stay consistent.
schedule = Path("schedule.html")
s = schedule.read_text(encoding="utf-8")
october = """<article class="event" id="october-2026"><div class="event-head"><div class="date">2026年10月27日（火）17:30〜21:35</div><h2>10月度 定例勉強会</h2></div><div class="body"><div class="theme">稲盛塾長講話DVD「経営問答シリーズ」</div><p><strong>日時：</strong>10月27日（火）17:30〜21:35（17:15受付開始）<br><strong>会場：</strong>Green セミナールーム Chiba<br>千葉市富士見2-8-14 エキニア千葉ビル4F<br><strong>参加方法：</strong>会場・Zoom</p><div style="background:var(--soft);border-radius:16px;padding:17px 19px;margin:14px 0 18px"><strong style="color:var(--wine)">今回の学び｜3つの経営問答</strong><ol style="margin:9px 0 0;padding-left:23px"><li>No.1 社員のやる気を引き出す（18分）</li><li>No.3 やりがいや充実感を持てる会社をどのように築くか（18分）</li><li>No.17 自らの思いを全社員に浸透させるには（26分）</li></ol><p style="margin:8px 0 0;font-size:14px">各講話の後に20分間のディスカッションを行います。</p></div><details style="border:1px solid var(--line);border-radius:16px;overflow:hidden"><summary style="cursor:pointer;padding:15px 18px;font-weight:900;color:var(--wine)">当日の進行予定・詳細を見る</summary><div style="border-top:1px solid var(--line);padding:15px 18px"><h3 style="font-size:17px;margin:0 0 8px;color:var(--wine)">第1部｜勉強会（会場・Zoom）</h3><p>17:15　受付開始<br>17:30　開会・開会挨拶<br>17:35　塾長講話DVD視聴・各講話後ディスカッション（各20分）<br>19:40　各グループから学びのまとめを発表<br>20:00　閉会挨拶</p><h3 style="font-size:17px;margin:18px 0 8px;color:var(--wine)">第2部｜コンパ</h3><p>20:10　開会挨拶・乾杯、歓談・ディスカッション<br>21:15　中締め・事務連絡<br>21:35　閉会</p><p style="font-size:13px">※終了時間は多少前後する場合があります。</p></div></details><a class="btn" href="https://chouseisan.com/s?h=36ade49b0c16413abab1e1b11fbbc8d7" target="_blank" rel="noopener noreferrer">出欠を回答する（調整さん） →</a><div style="background:#fff8f9;border:1px solid #e8dadd;border-radius:14px;padding:14px 17px;margin-top:14px;font-size:14px;line-height:1.8"><strong>回答締切：10月20日（火）</strong><br>欠席の場合も回答フォームへの入力をお願いします。<br>出席回答後、やむを得ず欠席される場合は前日までにご連絡ください。<br>※当日キャンセルはキャンセル料を頂戴いたします。</div></div></article>"""
s, count = re.subn(r'<article class="event">(?:(?!<article class="event">).)*?2026年10月27日（火）(?:(?!<article class="event">).)*?</article>', lambda _: october, s, count=1, flags=re.S)
if count != 1:
    raise RuntimeError("October schedule event not found")
schedule.write_text(s, encoding="utf-8")

homepage = Path("index.html")
s = homepage.read_text(encoding="utf-8")
home = """<section id="next" class="next"><div class="wrap"><div class="section-title"><div class="eyebrow">NEXT MEETING</div><h2>次回勉強会</h2></div><div class="event"><div class="event-head"><div>2026年10月27日（火）17:30〜21:35</div><h2>10月度 定例勉強会</h2></div><div class="event-body"><div class="meta-grid"><div class="meta"><strong>日時</strong><br>10月27日（火）17:30〜21:35</div><div class="meta"><strong>会場</strong><br>Green セミナールーム Chiba</div><div class="meta"><strong>参加方法</strong><br>会場・Zoom<br>千葉市富士見2-8-14 エキニア千葉ビル4F</div></div><div class="theme"><div class="eyebrow">MAIN THEME</div><h3>稲盛塾長講話DVD「経営問答シリーズ」</h3><p>社員のやる気、やりがいのある会社づくり、思いを全社員に浸透させる方法を、3つの講話とディスカッションから学びます。</p></div><div class="actions"><a class="btn btn-secondary" href="schedule.html#october-2026">講話テーマ・当日の進行を見る →</a></div><div style="margin-top:16px"><a class="btn btn-primary" href="https://chouseisan.com/s?h=36ade49b0c16413abab1e1b11fbbc8d7" target="_blank" rel="noopener noreferrer">出欠を回答する（調整さん） →</a></div><div style="background:#fff8f9;border:1px solid #e8dadd;border-radius:14px;padding:14px 17px;margin-top:14px;font-size:14px;line-height:1.8"><strong>回答締切：10月20日（火）</strong><br>欠席の場合も回答フォームへの入力をお願いします。<br>出席回答後、やむを得ず欠席される場合は前日までにご連絡ください。<br>※当日キャンセルはキャンセル料を頂戴いたします。</div></div></div></div></section>"""
s, count = re.subn(r'<section id="next" class="next">.*?</section>\s*(?=<section id="about">)', lambda _: home + "\n", s, count=1, flags=re.S)
if count != 1:
    raise RuntimeError("Homepage next event not found")
homepage.write_text(s, encoding="utf-8")

member = Path("member.html")
s = member.read_text(encoding="utf-8")
new_member = """<section><div class="wrap"><div class="section-title"><h2>次回の勉強会</h2><p>2026年10月27日（火）</p></div><article class="card" style="min-height:0"><div class="icon">📘</div><h3>10月度 定例勉強会｜経営問答シリーズ</h3><p>17:30〜21:35／Green セミナールーム Chiba（会場・Zoom）。社員のやる気、やりがいのある会社づくり、思いを全社員に浸透させることを学びます。</p><a class="btn" href="schedule.html#october-2026">講話テーマ・進行予定を見る →</a><div style="margin-top:12px"><a class="btn" href="https://chouseisan.com/s?h=36ade49b0c16413abab1e1b11fbbc8d7" target="_blank" rel="noopener noreferrer">出欠を回答する（調整さん） →</a></div><p style="font-size:13px;line-height:1.8"><strong>回答締切：10月20日（火）</strong><br>欠席の場合も回答をお願いします。<br>出席回答後に欠席される場合は前日までにご連絡ください。当日キャンセルはキャンセル料を頂戴いたします。</p></article></div></section>"""
s, count = re.subn(r'<section><div class="wrap"><div class="section-title"><h2>次回の勉強会</h2>.*?</section>', lambda _: new_member, s, count=1, flags=re.S)
if count != 1:
    raise RuntimeError("Member next meeting not found")
member.write_text(s, encoding="utf-8")

# LINE group menu > participation applications.
# September's finished event was removed earlier by archive_september_patch.py.
entry = Path("entry.html")
e = entry.read_text(encoding="utf-8")
oct_entry = """<section class="event" id="october-2026">
<div class="event-content">
<div class="event-type">心を高める経営を伸ばす会｜10月度 定例勉強会</div>
<h2>10月27日（火）経営問答シリーズ</h2>
<div class="info"><strong>2026年10月27日（火）17:30〜21:35</strong><br>受付開始 17:15<br>Green セミナールーム Chiba<br>千葉市富士見2-8-14 エキニア千葉ビル4F<br>勉強会は会場・Zoom参加に対応</div>
<div class="summary"><strong>稲盛塾長講話DVD「経営問答シリーズ」</strong><br>① No.1 社員のやる気を引き出す（18分）<br>② No.3 やりがいや充実感を持てる会社をどのように築くか（18分）<br>③ No.17 自らの思いを全社員に浸透させるには（26分）<br>各講話の後に20分間のディスカッションを行います。</div>
<details class="details"><summary>当日の進行予定を見る</summary><div class="detail-body"><h3>勉強会（会場・Zoom）</h3><p>17:15　受付開始<br>17:30　開会・開会挨拶<br>17:35　塾長講話DVD視聴・各講話後ディスカッション<br>19:40　各グループから学びのまとめを発表<br>20:00　閉会挨拶</p><h3>コンパ</h3><p>20:10　開会挨拶・乾杯、歓談・ディスカッション<br>21:15　中締め・事務連絡<br>21:35　閉会</p><p>※終了時間は多少前後する場合があります。</p></div></details>
<a class="button" href="https://chouseisan.com/s?h=36ade49b0c16413abab1e1b11fbbc8d7" target="_blank" rel="noopener noreferrer">10月勉強会の出欠を回答する（調整さん） →</a>
<div class="summary" style="margin-top:14px"><strong>回答締切：10月20日（火）</strong><br>欠席の場合も回答フォームへ入力をお願いします。<br>出席回答後、やむを得ず欠席される場合は前日までにご連絡ください。<br>※当日キャンセルはキャンセル料を頂戴いたします。</div>
</div></section>"""
if 'id="october-2026"' not in e:
    marker = '<section class="event" id="world">'
    if marker not in e:
        raise RuntimeError("LINE entry event insertion point not found")
    e = e.replace(marker, oct_entry + "\\n" + marker, 1)
entry.write_text(e, encoding="utf-8")
