from pathlib import Path
p=Path('schedule.html')
s=p.read_text(encoding='utf-8')
if '.agenda-details{' not in s:
    s=s.replace('.info{background:var(--soft);border-radius:20px;padding:22px;color:var(--muted)}', '.agenda-details{margin-top:16px;border:1px solid var(--line);border-radius:16px;overflow:hidden;background:#fff}.agenda-details summary{cursor:pointer;padding:15px 17px;font-weight:900;color:var(--wine);list-style:none}.agenda-details summary::-webkit-details-marker{display:none}.agenda-details summary:after{content:"＋";float:right}.agenda-details[open] summary:after{content:"−"}.agenda-content{padding:2px 17px 18px;border-top:1px solid var(--line);font-size:14px}.agenda-content>p{color:var(--ink)}.agenda-block{margin:14px 0;padding:13px 14px;border-left:4px solid var(--wine);background:#fff8f9;border-radius:0 12px 12px 0}.agenda-block h3{margin:0 0 5px;color:var(--wine);font-size:16px}.agenda-block h4{margin:12px 0 4px}.agenda-block p{margin:5px 0;color:var(--ink)}.agenda-block ul{margin:6px 0 0;padding-left:20px}.agenda-block li{margin:4px 0}.info{background:var(--soft);border-radius:20px;padding:22px;color:var(--muted)}')
needle='<a class="btn" href="entry.html#september">参加申込・出欠登録</a>'
agenda='''<a class="btn" href="entry.html#september">参加申込・出欠登録</a><details class="agenda-details"><summary>当日の進行予定を見る</summary><div class="agenda-content"><p><strong>日時：</strong>2026年9月29日（火）18:00～21:00<br><strong>会場：</strong>グリーンセミナールーム（千葉市中央区）</p><p>経営12ヵ条 第4条「誰にも負けない努力をする」と、フィロソフィ「ベクトルを揃える」を学びます。講義だけでなく、自分自身や自社に置き換えて考えるグループディスカッションも行います。</p><div class="agenda-block"><h3>18:00～18:10　開会</h3><ul><li>経営12ヵ条チェックシート</li><li>勉強会の目的確認</li></ul></div><div class="agenda-block"><h3>18:10～19:30　第1部</h3><p><strong>経営12ヵ条 第4条「誰にも負けない努力をする」</strong></p><p>～地味な仕事を一歩一歩堅実に、弛まぬ努力を続ける～</p><h4>テーマ</h4><ul><li>塾長は、なぜ誰にも負けない努力を続けることができたのか</li><li>「自分なりの努力」と「誰にも負けない努力」の違い</li><li>努力を続けるために大切なこと</li><li>経営者の本気の努力が、周囲にもたらすもの</li><li>従業員が自ら努力する会社にするために、経営者は何をすべきか</li></ul><h4>グループディスカッション</h4></div><div class="agenda-block"><h3>19:30～20:10　第2部</h3><p><strong>フィロソフィ「ベクトルを揃える」</strong></p><ul><li>なぜ、組織のベクトルを揃える必要があるのか</li><li>全員が同じ目的、同じ方向に向かうために大切なこと</li><li>経営者の思いを、どのように従業員へ伝えるのか</li><li>一人ひとりの努力を、組織の大きな力に変えるには</li></ul></div><div class="agenda-block"><h3>20:10～21:00　第3部</h3><p><strong>京セラ式コンパ</strong></p><p>「ベクトルを揃える」をテーマにして、それぞれの経営・仕事での実践について本音で語り合います。</p></div><div class="agenda-block"><h3>21:00　閉会</h3></div></div></details>'''
if needle in s and 'class="agenda-details"' not in s:
    s=s.replace(needle,agenda,1)
p.write_text(s,encoding='utf-8')
